// ============================================================
// LightMCP — Uninstall Script Generator
// Generates a standalone ~/.lightmcp/uninstall.cjs script at setup
// time. The generated script has all paths hardcoded and can run
// independently — even after the LightMCP project is deleted.
// ============================================================
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import type { DetectedAgent } from "./scanner.js";

const UNINSTALL_DIR = path.join(os.homedir(), ".lightmcp");
const SCRIPT_PATH = path.join(UNINSTALL_DIR, "uninstall.cjs");

export function getUninstallScriptPath(): string {
  return SCRIPT_PATH;
}

export function scriptExists(): boolean {
  return existsSync(SCRIPT_PATH);
}

function allAntigravityPaths(homeDir: string): string[] {
  const paths: string[] = [];
  const candidateDirs = [
    path.join(homeDir, ".gemini", "config"),
    path.join(homeDir, ".gemini", "antigravity"),
  ];
  for (const dir of candidateDirs) {
    const p = path.join(dir, "mcp_config.json");
    if (existsSync(p)) paths.push(p);
  }
  if (process.platform === "win32") {
    const vscode = path.join(process.env.APPDATA ?? "", "Code", "User", "globalStorage", "google.antigravity", "mcp_config.json");
    if (existsSync(path.dirname(vscode)) || existsSync(vscode)) paths.push(vscode);
  } else {
    const vscodeLinux = path.join(homeDir, ".config", "Code", "User", "globalStorage", "google.antigravity", "mcp_config.json");
    if (existsSync(vscodeLinux)) paths.push(vscodeLinux);
  }
  return paths;
}

interface AgentScriptData {
  name: string;
  configPath: string;
  configExists: boolean;
  hasLightMCP: boolean;
  backupPath: string;
}

interface RuleScriptData {
  name: string;
  filePath: string;
}

interface ScriptPayload {
  platform: string;
  lightmcpRoot: string;
  configPath: string;
  sessionFile: string;
  uninstallDir: string;
  agents: AgentScriptData[];
  ruleFiles: RuleScriptData[];
  cwdFiles: string[];
  extraBackups: string[];
  extraAgentConfigs: string[];
  vbsPath: string;
}

export function generateUninstallScript(
  agents: DetectedAgent[],
  configPath: string,
  lightmcpRoot: string,
): string {
  if (!existsSync(UNINSTALL_DIR)) {
    mkdirSync(UNINSTALL_DIR, { recursive: true });
  }

  const homeDir = os.homedir();

  const agentData: AgentScriptData[] = agents.map((a) => ({
    name: a.name,
    configPath: a.configPath,
    configExists: a.configExists,
    hasLightMCP: a.hasLightMCP,
    backupPath: path.join(path.dirname(a.configPath), "lightmcp_servers.json"),
  }));

  // Deduplicated rule files (openCode CLI + Desktop share AGENTS.md)
  const ruleFiles: RuleScriptData[] = [
    { name: "Antigravity", filePath: path.join(homeDir, ".gemini", "GEMINI.md") },
    { name: "Claude Code", filePath: path.join(homeDir, ".claude", "CLAUDE.md") },
    { name: "openCode", filePath: path.join(homeDir, ".config", "opencode", "AGENTS.md") },
    { name: "Cursor", filePath: path.join(homeDir, ".cursor", "rules", "lightmcp.mdc") },
  ];

  const payload: ScriptPayload = {
    platform: process.platform,
    lightmcpRoot,
    configPath,
    sessionFile: path.join(os.tmpdir(), "lightmcp_session.json"),
    uninstallDir: UNINSTALL_DIR,
    agents: agentData,
    ruleFiles,
    cwdFiles: ["tool_catalog.json", "tool_tips.json"],
    extraBackups: [
      path.join(homeDir, ".gemini", "antigravity", "lightmcp_servers.json"),
      path.join(homeDir, "lightmcp_servers.json"),
    ],
    extraAgentConfigs: allAntigravityPaths(homeDir),
    vbsPath: path.join(lightmcpRoot, "start_hidden.vbs"),
  };

  const script = buildScript(payload);
  writeFileSync(SCRIPT_PATH, script, "utf-8");
  return SCRIPT_PATH;
}

function buildScript(payload: ScriptPayload): string {
  const json = JSON.stringify(payload, null, 2);
  const serialized = json.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

  return `#!/usr/bin/env node
// ============================================================
// LightMCP — Complete Uninstall Script
// Generated by: lightmcp setup
// ============================================================
// Runs independently — does NOT depend on LightMCP source files.
//
// Usage:  node ~/.lightmcp/uninstall.cjs
//
// This script:
//   1. Kills running LightMCP & Ollama processes
//   2. Restores agent MCP configs to pre-LightMCP state
//   3. Cleans up all artifacts (backups, tmp, rules, catalog, config)
//   4. Removes the global CLI binary (npm uninstall -g)
//   5. Deletes the entire LightMCP project directory
//   6. Self-destructs
// ============================================================

"use strict";

var fs = require("fs");
var path = require("path");
var os = require("os");
var cp = require("child_process");

// === Embedded data (hardcoded at setup time) ===
var DATA = ${serialized};

// === Helpers ===
var exists = function(p) { try { return fs.existsSync(p); } catch(e) { return false; } };
var read = function(p) { try { return JSON.parse(fs.readFileSync(p, "utf-8")); } catch(e) { return null; } };
var write = function(p, o) { try { fs.writeFileSync(p, JSON.stringify(o, null, 2) + "\\n", "utf-8"); } catch(e) {} };
var rm = function(p) { if (exists(p)) { try { fs.rmSync(p); } catch(e) {} } };
var rmdir = function(p) { if (exists(p)) { try { fs.rmSync(p, { recursive: true, force: true }); } catch(e) {} } };
var run = function(cmd, opts) { try { return cp.execSync(cmd, Object.assign({ stdio: "pipe" }, opts || {})); } catch(e) { return null; } };
var sleep = function(ms) { var end = Date.now() + ms; while (Date.now() < end) {} };
var RULE_START = "\\\\x3C!-- LIGHTMCP_RULE_START --\\\\x3E";
var RULE_END   = "\\\\x3C!-- LIGHTMCP_RULE_END --\\\\x3E";

// === Banner ===
console.log("");
console.log("============================================================");
console.log("  LightMCP — Complete Uninstall");
console.log("============================================================");
console.log("");

// === Step 1: Kill processes ===
console.log("[1/9] Stopping LightMCP processes...");
if (DATA.platform === "win32") {
  try { cp.execSync('powershell -Command "Get-Process node* -ErrorAction SilentlyContinue | Where-Object {$_.CommandLine -like ""*lightmcp*""} | Stop-Process -Force -ErrorAction SilentlyContinue"', { stdio: "pipe" }); } catch(e) {}
} else {
  run("pkill -f 'lightmcp' 2>/dev/null || true");
}
sleep(500);
console.log("  [OK]");

console.log("[2/9] Stopping Ollama...");
if (DATA.platform === "win32") {
  try { cp.execSync('taskkill /F /IM ollama.exe 2>nul', { stdio: "pipe" }); } catch(e) {}
  try { cp.execSync('taskkill /F /IM "Ollama app.exe" 2>nul', { stdio: "pipe" }); } catch(e) {}
} else {
  run("pkill -f ollama 2>/dev/null || true");
}
sleep(500);
console.log("  [OK]");

// === Step 3: Restore agent configurations ===
console.log("[3/9] Restoring agent configurations...");
for (var i = 0; i < DATA.agents.length; i++) {
  var agent = DATA.agents[i];
  var bp = agent.backupPath;

  if (exists(bp)) {
    var backup = read(bp);
    if (backup && backup.mcpServers) {
      var keys = Object.keys(backup.mcpServers);
      for (var k = 0; k < keys.length; k++) {
        if (backup.mcpServers[keys[k]] && backup.mcpServers[keys[k]]._removed) {
          delete backup.mcpServers[keys[k]];
        }
      }
      write(agent.configPath, backup);
      console.log("  [OK] Restored " + agent.name + " to original config");
    } else {
      console.log("  [WARN] Invalid backup for " + agent.name);
    }
    rm(bp);
  } else if (agent.configExists && agent.hasLightMCP) {
    var current = read(agent.configPath);
    if (current && current.mcpServers) {
      delete current.mcpServers.lightmcp;
      write(agent.configPath, current);
      console.log("  [OK] Removed LightMCP from " + agent.name);
    }
  }
  rm(agent.configPath + ".backup");
  rm(agent.configPath + ".tmp");
}

for (var b = 0; b < DATA.extraBackups.length; b++) { rm(DATA.extraBackups[b]); }

// Also clean lightmcp from any extra Antigravity config paths the scanner may have missed
console.log("[3b] Checking extra agent configs...");
for (var e = 0; e < DATA.extraAgentConfigs.length; e++) {
  var ec = DATA.extraAgentConfigs[e];
  if (!exists(ec)) continue;
  try {
    var current = JSON.parse(fs.readFileSync(ec, "utf-8"));
    if (current && current.mcpServers && current.mcpServers.lightmcp) {
      delete current.mcpServers.lightmcp;
      write(ec, current);
      console.log("  [OK] Removed LightMCP from " + ec);
    }
  } catch(ex) {
    console.log("  [WARN] Could not process " + ec);
  }
  rm(ec + ".backup");
  rm(ec + ".tmp");
}
console.log("  [OK]");

// === Step 4: Remove agent rules ===
console.log("[4/9] Removing agent rules...");
var RULE_START = "\\\\x3C!-- LIGHTMCP_RULE_START --\\\\x3E";
var RULE_END   = "\\\\x3C!-- LIGHTMCP_RULE_END --\\\\x3E";
for (var r = 0; r < DATA.ruleFiles.length; r++) {
  var rule = DATA.ruleFiles[r];
  if (!exists(rule.filePath)) continue;

  try {
    var content = fs.readFileSync(rule.filePath, "utf-8");
    var si = content.indexOf(RULE_START);
    if (si === -1) continue;
    var ei = content.indexOf(RULE_END, si);
    if (ei === -1) continue;

    var before = content.slice(0, si).trimEnd();
    var after = content.slice(ei + RULE_END.length).trimStart();
    var cleaned = before;
    if (after) cleaned = cleaned ? cleaned + "\\n\\n" + after : after;

    if (!cleaned.trim()) {
      rm(rule.filePath);
    } else {
      fs.writeFileSync(rule.filePath, cleaned.trim() + "\\n", "utf-8");
    }
    console.log("  [OK] " + rule.name + " rule removed");
  } catch(e) {
    console.log("  [WARN] Could not process " + rule.name + " rule");
  }
}
console.log("  [OK]");

// === Step 5: Delete generated files ===
console.log("[5/9] Deleting generated files...");
for (var f = 0; f < DATA.cwdFiles.length; f++) {
  rm(path.resolve(process.cwd(), DATA.cwdFiles[f]));
}
console.log("  [OK]");

// === Step 6: Delete generated config artifacts (preserve lightmcp_config.json) ===
console.log("[6/9] Cleaning up config artifacts...");
rm(DATA.configPath + ".tmp");
rm(DATA.configPath + ".backup");
rm(DATA.sessionFile);
console.log("  [OK] (lightmcp_config.json preserved — delete manually if desired)");

// === Step 7: Platform-specific cleanup ===
console.log("[7/9] Removing system integrations...");
if (DATA.platform === "win32") {
  try { cp.execSync('powershell -Command "Unregister-ScheduledTask -TaskName ""LightMCP_AutoStart"" -Confirm:$false -ErrorAction SilentlyContinue"', { stdio: "pipe" }); } catch(e) {}
  rm(DATA.vbsPath);
  console.log("  [OK] Windows startup task and VBS launcher removed");
} else {
  run("systemctl --user disable lightmcp.service 2>/dev/null || true");
  run("systemctl --user daemon-reload 2>/dev/null || true");
  rm(path.join(os.homedir(), ".config", "systemd", "user", "lightmcp.service"));
  console.log("  [OK] Linux systemd service removed");
}

// === Step 8: Remove global CLI binary ===
console.log("[8/9] Removing global CLI binary (npm uninstall -g)...");
var npmOut = run("npm uninstall -g lightmcp 2>&1", { timeout: 30000 });
if (npmOut !== null) {
  console.log("  [OK] npm global package removed");
} else {
  console.log("  [WARN] Could not remove npm global package.");
  console.log("  Run manually: npm uninstall -g lightmcp");
}

// === Step 9: Delete project directory + self-destruct ===
console.log("[9/9] Deleting LightMCP project directory...");
console.log("  Path: " + DATA.lightmcpRoot);
rmdir(DATA.lightmcpRoot);
if (exists(DATA.lightmcpRoot)) {
  console.log("  [WARN] Could not fully delete project directory.");
  console.log("  Some files may be locked by other processes.");
  console.log("  Manually delete: " + DATA.lightmcpRoot);
} else {
  console.log("  [OK] Project directory deleted");
}

// Self-delete — try immediate deletion, then schedule via detached process if still locked
console.log("");
console.log("Self-destruct...");
rmdir(DATA.uninstallDir);
if (exists(DATA.uninstallDir)) {
  console.log("  Scheduling deferred cleanup (file still in use)...");
  if (DATA.platform === "win32") {
    var deferred = cp.spawn("powershell", ["-NoProfile", "-Command", "Start-Sleep -Seconds 3; Remove-Item -LiteralPath '" + DATA.uninstallDir + "' -Recurse -Force -ErrorAction SilentlyContinue"], { detached: true, stdio: "ignore" });
    deferred.unref();
  } else {
    var deferred = cp.spawn("sh", ["-c", "sleep 3 && rm -rf '" + DATA.uninstallDir + "'"], { detached: true, stdio: "ignore" });
    deferred.unref();
  }
  console.log("  The ~/.lightmcp/ directory will be removed shortly.");
} else {
  console.log("  [OK] Cleaned up");
}

console.log("");
console.log("============================================================");
console.log("  LightMCP has been fully uninstalled.");
console.log("  - lightmcp_config.json preserved for reinstall.");
console.log("  - The ~/.lightmcp/ directory will disappear shortly.");
console.log("  - Uninstall Ollama separately if no longer needed.");
console.log("============================================================");
console.log("");
`;
}
